# Generated by Django 5.1.1 on 2024-12-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
