# Generated by Django 5.1.1 on 2024-11-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('difficulty', models.TextField(max_length=10)),
                ('interest', models.TextField(max_length=30)),
            ],
        ),
    ]
