# Generated by Django 5.1.1 on 2024-12-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskGenerator', '0004_alter_completedtask_confirmed_confirmationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationtask',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
