# Generated by Django 5.1.1 on 2024-12-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskGenerator', '0005_confirmationtask_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationtask',
            name='confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
