# Generated by Django 5.1.1 on 2024-12-18 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskGenerator', '0006_alter_confirmationtask_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationtask',
            name='doer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_tasks_as_doer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confirmationtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_tasks_as_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
